/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\optimized-room.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/optimized-room.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.063, 0]} scale={0.779}>
        <group position={[1.717, -3.64, -3.087]} scale={2.651}>
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['PC_Plastic Color']} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials['PC_Glass Cleared']} />
          <mesh geometry={nodes.Cube001_3.geometry} material={materials.PC_Bolts} />
          <mesh geometry={nodes.Cube001_4.geometry} material={materials.PC_Rig} />
          <mesh geometry={nodes.Cube001_5.geometry} material={materials.PC_RGB} />
          <mesh geometry={nodes.Cube001_6.geometry} material={materials.PC_Button} />
          <mesh geometry={nodes.Cube001_7.geometry} material={materials.PC_Glass_Frosted} />
          <mesh geometry={nodes.Cube001_8.geometry} material={materials['PC_Magnetic Metal']} />
          <mesh geometry={nodes.Cube001_9.geometry} material={materials['PC_Rig 2']} />
          <mesh geometry={nodes.Cube001_10.geometry} material={materials.PC_Stainless} />
          <mesh geometry={nodes.Cube001_11.geometry} material={materials['PC_Red Alloy']} />
          <mesh geometry={nodes.Cube001_12.geometry} material={materials['PC_Fan Metal']} />
          <mesh geometry={nodes.Cube001_13.geometry} material={materials['PC_Color Emission']} />
          <mesh geometry={nodes.Cube001_14.geometry} material={materials['PC_Fan Gray']} />
          <mesh geometry={nodes.Cube001_15.geometry} material={materials.PC_GPU_MBoard} />
          <mesh geometry={nodes.Cube001_16.geometry} material={materials.PC_MB_Ports} />
          <mesh geometry={nodes.Cube001_17.geometry} material={materials['PC_Heat Sink']} />
          <mesh geometry={nodes.Cube001_18.geometry} material={materials.PC_RAM} />
          <mesh geometry={nodes.Cube001_19.geometry} material={materials.PC_GPU_Slot} />
          <mesh geometry={nodes.Cube001_20.geometry} material={materials.PC_GPU_White} />
          <mesh geometry={nodes.Cube001_21.geometry} material={materials.PC_GPU_Gray} />
          <mesh geometry={nodes.Cube001_22.geometry} material={materials.PC_GPU_Geforce} />
          <mesh geometry={nodes.Cube001_23.geometry} material={materials['PC_Base Foot']} />
        </group>
      </group>
      <group position={[-2.325, 0.294, -2.881]} scale={1.309}>
        <mesh geometry={nodes.LDesk_Supports.geometry} material={materials['Metal Dark']} />
        <mesh geometry={nodes.LTable_Feet001.geometry} material={materials['Metal Shiny']} position={[0.279, 0, 1.917]} />
        <mesh geometry={nodes.LTable_Feet002.geometry} material={materials['Metal Shiny']} position={[0.279, 0, 0.066]} />
        <mesh geometry={nodes.LTable_Feet003.geometry} material={materials['Metal Shiny']} position={[1.237, 0, 0.069]} />
        <mesh geometry={nodes.LTable_Feet004.geometry} material={materials['Metal Shiny']} position={[3.027, 0, 0.695]} />
        <mesh geometry={nodes.LTable_Feet005.geometry} material={materials['Metal Shiny']} position={[3.027, 0, 0.078]} />
        <mesh geometry={nodes.ltable_top.geometry} material={materials['Metal Dark']} />
        <mesh geometry={nodes.ltable_top_1.geometry} material={materials['Metal Shiny']} />
        <mesh geometry={nodes.ltable_top_2.geometry} material={materials['Plastic Black']} />
      </group>
      <group position={[-1.383, 2.004, -1.998]} rotation={[0, -0.364, 0]} scale={0.435}>
        <mesh geometry={nodes.КриваяБезье001.geometry} material={materials['Wire.001']} position={[-1.182, 1.784, 0]} />
        <group position={[0, 1.953, 0]}>
          <mesh geometry={nodes.Куб006.geometry} material={materials['Plastic .001']} />
          <mesh geometry={nodes.Куб006_1.geometry} material={materials['Lamp.003']} />
        </group>
        <mesh geometry={nodes.Куб001.geometry} material={nodes.Куб001.material} position={[-0.887, 1.931, 0]} />
        <group position={[-0.701, -0.268, 0]}>
          <mesh geometry={nodes.Цилиндр002.geometry} material={materials['Plastic .001']} />
          <mesh geometry={nodes.Цилиндр002_1.geometry} material={materials['Plastic Black.001']} />
        </group>
        <group position={[-0.52, -0.188, 0]}>
          <mesh geometry={nodes.Цилиндр001_1.geometry} material={materials['Plastic .001']} />
          <mesh geometry={nodes.Цилиндр001_2.geometry} material={materials['Plastic Black.001']} />
        </group>
      </group>
      <group position={[0, 1.885, -2.326]} scale={1.904}>
        <mesh geometry={nodes.base.geometry} material={materials.base} position={[0, 0.007, 0]} />
        <mesh geometry={nodes.joint.geometry} material={materials.black} position={[0, 0.007, 0]} />
        <mesh geometry={nodes.light.geometry} material={materials.light} position={[0, 0.007, 0]} />
        <mesh geometry={nodes.power_unit.geometry} material={materials['power unit']} position={[0, 0.007, 0]} />
        <mesh geometry={nodes.thread.geometry} material={materials.black} position={[0, 0.007, 0]} />
        <group position={[0.078, 0.001, -0.233]} rotation={[0, -1.407, 0]}>
          <mesh geometry={nodes.Plane010.geometry} material={materials['power unit']} />
          <mesh geometry={nodes.Plane010_1.geometry} material={materials.chromium} />
          <mesh geometry={nodes.Plane010_2.geometry} material={materials.black} />
          <mesh geometry={nodes.Plane010_3.geometry} material={materials.hookup} />
        </group>
      </group>
      <group position={[0.482, 1.925, -2.255]} scale={1.762}>
        <mesh geometry={nodes.Vert001.geometry} material={materials['IMac-Body']} rotation={[Math.PI, 0, Math.PI]} />
      </group>
      <group position={[0, 0.257, -1.517]} rotation={[Math.PI, -0.065, Math.PI]} scale={1.988}>
        <mesh geometry={nodes.NurbsPath.geometry} material={materials.fabric} position={[0, 0.457, -0.286]} scale={[0.138, 0.156, 0.156]} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials['chrome metal']} position={[0, 0.457, -0.295]} scale={[0.138, 0.156, 0.156]} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials['plastic smooth']} position={[0, 0.457, -0.384]} scale={[0.138, 0.156, 0.156]} />
        <group position={[0, 0.032, 0]} scale={0.989}>
          <mesh geometry={nodes.Plane021.geometry} material={materials['chrome metal']} />
          <mesh geometry={nodes.Plane021_1.geometry} material={materials['metal painted']} />
        </group>
        <group position={[0, 0.032, 0]} scale={0.989}>
          <mesh geometry={nodes.Plane020.geometry} material={materials['chrome metal']} />
          <mesh geometry={nodes.Plane020_1.geometry} material={materials['metal painted']} />
        </group>
        <mesh geometry={nodes.Office_chair004.geometry} material={materials['Leather Base 01 Holes']} position={[0, 0.032, 0]} scale={0.989} />
        <mesh geometry={nodes.Office_chair006.geometry} material={materials['plastic smooth']} position={[0, 0.032, 0]} scale={0.989} />
        <group position={[0, 0.032, 0]} scale={0.989}>
          <mesh geometry={nodes.Plane017.geometry} material={materials['fabric.001']} />
          <mesh geometry={nodes.Plane017_1.geometry} material={materials.fabric} />
        </group>
        <mesh geometry={nodes.Office_chair008.geometry} material={materials['chrome metal']} position={[0, 0.032, 0]} scale={0.156} />
        <group position={[0, 0.032, 0]} scale={0.989}>
          <mesh geometry={nodes.Plane014.geometry} material={materials['chrome metal']} />
          <mesh geometry={nodes.Plane014_1.geometry} material={materials['plastic black rough']} />
          <mesh geometry={nodes.Plane014_2.geometry} material={materials['metal painted']} />
          <mesh geometry={nodes.Plane014_3.geometry} material={materials['plastic smooth']} />
        </group>
        <mesh geometry={nodes.Office_chair010.geometry} material={materials['metal painted']} position={[0, 0.032, 0]} scale={0.989} />
        <mesh geometry={nodes.Plane.geometry} material={materials['fabric.001']} position={[0, 0.457, -0.302]} scale={[0.156, 0.156, 0.128]} />
        <mesh geometry={nodes.Plane002.geometry} material={materials.fabric} position={[0, 0.457, -0.302]} scale={[0.156, 0.156, 0.128]} />
        <mesh geometry={nodes.Plane006.geometry} material={materials['metal painted']} position={[0, 0.457, -0.302]} scale={[0.156, 0.156, 0.128]} />
      </group>
      <group position={[1.235, 1.885, -2.405]} scale={1.722}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['silver 1']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.Label} />
        <group position={[-0.006, 0.136, 0.004]} rotation={[0.025, -0.953, 0.021]} scale={[0.008, 0.006, 0.008]}>
          <mesh geometry={nodes.Plane022.geometry} material={materials['silver 1.001']} />
          <mesh geometry={nodes.Plane022_1.geometry} material={materials['silver 2']} />
        </group>
      </group>
      <group position={[0, 0.244, -0.965]} rotation={[-Math.PI, 0.013, -Math.PI]}>
        <primitive object={nodes.spine} />
      </group>
      <group position={[-0.018, 0.004, -1.017]} rotation={[-Math.PI, 0.04, -Math.PI]}>
        <primitive object={nodes.root} />
        <primitive object={nodes['MCH-torsoparent']} />
        <primitive object={nodes['MCH-hand_ikparentL']} />
        <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
        <primitive object={nodes['MCH-hand_ikparentR']} />
        <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
        <primitive object={nodes['MCH-foot_ikparentL']} />
        <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
        <primitive object={nodes['MCH-foot_ikparentR']} />
        <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
        <primitive object={nodes.neutral_bone} />
        <skinnedMesh geometry={nodes.model.geometry} material={materials.CustomMaterial} skeleton={nodes.model.skeleton} />
      </group>
      <group position={[0, 0, 2.179]}>
        <group position={[-3.29, 1.615, -2.307]} rotation={[Math.PI / 2, 0, -1.577]} scale={1.195}>
          <mesh geometry={nodes.Cylinder002.geometry} material={materials['NA Aluminium.002']} />
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['NA Aluminium.002']} />
          <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Gasket.002']} />
          <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Window Glass.002']} />
        </group>
      </group>
      <group position={[-0.173, 1.904, -2.45]} scale={1.338}>
        <group position={[0.411, 0.363, -0.005]} rotation={[0, 0, Math.PI]}>
          <group position={[0.411, 0, -0.116]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Monitor.geometry} material={materials.Metal} position={[0, 0, 0.045]}>
              <mesh geometry={nodes.ConicRing.geometry} material={materials.Transparent} />
              <mesh geometry={nodes.ControlPanel.geometry} material={materials.BlackGloss} />
              <mesh geometry={nodes.Hinge.geometry} material={materials['BlackPlastic Matte']} />
              <mesh geometry={nodes.Led.geometry} material={materials.Led} />
              <mesh geometry={nodes.Logo.geometry} material={materials.Logo} position={[0, -0.183, 0.02]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.OuterRing.geometry} material={materials.BlackGloss} />
              <mesh geometry={nodes.PowerButton.geometry} material={materials.Metal} />
              <mesh geometry={nodes.Samsung_Odyssey_Logo.geometry} material={materials.Samsung_Odyssey_Logo} position={[0, -0.363, 0.076]} />
              <mesh geometry={nodes.Screen.geometry} material={materials.Screen} />
              <mesh geometry={nodes.ScreenBezel.geometry} material={materials.ScreenRim} />
              <mesh geometry={nodes.SpeakerGrill.geometry} material={materials.BlackGloss} />
              <mesh geometry={nodes.Cut.geometry} material={materials['BlackPlastic Matte']} />
              <mesh geometry={nodes.Cut_1.geometry} material={materials['Metal.001']} />
              <mesh geometry={nodes.LPattern52.geometry} material={materials['Metal.001']} />
              <mesh geometry={nodes.LPattern52_1.geometry} material={materials['BlackPlastic Matte']} />
              <mesh geometry={nodes.Sheet_387.geometry} material={materials['Metal.001']} />
              <mesh geometry={nodes.Sheet_387_1.geometry} material={materials['BlackPlastic Matte']} />
              <mesh geometry={nodes['USB-C_1'].geometry} material={materials['Metal.001']} />
              <mesh geometry={nodes['USB-C_2'].geometry} material={materials['BlackPlastic Matte']} />
              <mesh geometry={nodes['USB-C001_1'].geometry} material={materials['Metal.001']} />
              <mesh geometry={nodes['USB-C001_2'].geometry} material={materials['BlackPlastic Matte']} />
            </mesh>
          </group>
          <mesh geometry={nodes.Neck.geometry} material={materials['BlackPlastic Matte']} position={[0.411, 0, -0.116]} rotation={[0, 0, -Math.PI]} />
        </group>
        <mesh geometry={nodes.Base.geometry} material={materials.Metal}>
          <mesh geometry={nodes.Rail.geometry} material={materials['BlackPlastic Matte']} />
        </mesh>
      </group>
      <group position={[0, 2.386, 0.376]}>
        <group position={[-2.037, -0.37, -0.936]} rotation={[-Math.PI, 1.556, -Math.PI]} scale={1.787}>
          <mesh geometry={nodes.Cube019_1.geometry} material={materials['Translucent Plastic']} />
          <mesh geometry={nodes.Cube019_2.geometry} material={materials['cover.009']} />
          <mesh geometry={nodes.Cube019_3.geometry} material={materials.cover} />
          <mesh geometry={nodes.Cube019_4.geometry} material={materials['cover.001']} />
          <mesh geometry={nodes.Cube019_5.geometry} material={materials['cover.002']} />
          <mesh geometry={nodes.Cube019_6.geometry} material={materials['cover.003']} />
          <mesh geometry={nodes.Cube019_7.geometry} material={materials['cover.005']} />
          <mesh geometry={nodes.Cube019_8.geometry} material={materials['cover.004']} />
          <mesh geometry={nodes.Cube019_9.geometry} material={materials['cover.006']} />
          <mesh geometry={nodes.Cube019_10.geometry} material={materials['cover.007']} />
          <mesh geometry={nodes.Cube019_11.geometry} material={materials['cover.008']} />
        </group>
      </group>
      <group position={[2.286, 0.304, -2.529]} scale={1.86}>
        <mesh geometry={nodes.FloorLamp_Bulb.geometry} material={materials['Lamp Bulb']} />
        <mesh geometry={nodes.FloorLamp_Cover.geometry} material={materials.Material} position={[0, 1.368, 0]} />
        <mesh geometry={nodes.FloorLamp_Stem.geometry} material={materials['Plastic Black Shiny']} />
        <mesh geometry={nodes.FloorLamp_Wire.geometry} material={materials['Plastic Rubbery']} position={[0.006, 0.022, -0.006]} />
        <group position={[0.042, 0.177, -0.196]}>
          <mesh geometry={nodes.Cylinder005.geometry} material={materials['Plastic Black Insulator']} />
          <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Metal Chrome']} />
        </group>
      </group>
      <mesh geometry={nodes.Patch_Black_Carpet.geometry} material={materials['Carpet006.040']} position={[0.076, 0.291, 0]} scale={[3.104, 1.929, 2.134]} />
      <mesh geometry={nodes.Patch_Black_Carpet002.geometry} material={materials['Carpet006.040']} scale={2.08} />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.radiator_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.radiator_blinn1_0001.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.railing_blinn1_0.geometry} material={materials.blinn1} position={[-0.251, 0, 0]} />
      <mesh geometry={nodes.red_vac_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.vacuum1_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.vacuumgrey_blinn1_0.geometry} material={materials.blinn1} />
      <group position={[-3.29, 1.615, -2.307]} rotation={[Math.PI / 2, 0, -1.577]} scale={1.195}>
        <mesh geometry={nodes.Cylinder042.geometry} material={materials['NA Aluminium']} />
        <mesh geometry={nodes.Cylinder042_1.geometry} material={materials['NA Aluminium']} />
        <mesh geometry={nodes.Cylinder042_2.geometry} material={materials.Gasket} />
        <mesh geometry={nodes.Cylinder042_3.geometry} material={materials['Window Glass']} />
      </group>
      <mesh geometry={nodes.sheer.geometry} material={materials['white curtain']} position={[-2.43, 1.755, -1.446]} rotation={[0, -1.54, 0]} scale={1.297} />
      <mesh geometry={nodes.Keyboard.geometry} material={materials['Clean Keyboard']} position={[-0.197, 1.904, -2.253]} scale={1.44} />
    </group>
  )
}

useGLTF.preload('/optimized-room.glb')
